### ISSUE TITLE
Add travel info to the venue page

### ISSUE THREAD

**Issue by necamma** [carlthuringer/wedding#1]
Here is the content:

Travel Info
Parking is available for free onsite at the Center for Visual and Performing Arts. Click on the link in the map below for specific directions to the venue. 

Travelers from Chicago: 
Take I-90 E/I-94 E Express and I-94 E to Calumet Avenue in Hammond, IN. Take exit 1 from I-94 E. Continue on Calumet Avenue toward Ridge Road. Turn left on Ridge Road. In a quarter of a mile, destination will be on the right.

Travelers from Indiana:
Take the Calumet Avenue exit from I-94. Turn on Ridge Road heading east. Destination will be on the right. 

Travelers from Michigan: 
Take I-75 S to exit 53B to merge onto I-94 W toward Chicago. Take exit 1 for Calumet Avenue toward US-41 N. Merge onto Calumet Avenue. Turn left on to Ridge Road. Destination will be on the right in a quarter of a mile. 

Where to Stay
A block of hotel rooms will be made close to the Center for Visual and Performing Arts. There will be more details to come once available. 

![image](https://cloud.githubusercontent.com/assets/19656892/15659592/97368a70-2692-11e6-8503-3853254f60b8.png)

**Comment by carlthuringer** [comment]
Got it. Further styling will happen later.
