### ISSUE TITLE
Add new Event Details page

### ISSUE THREAD

**Issue by necamma** [carlthuringer/wedding#3]
Event Details

Saturday, June 3, 2017  |  5 p.m.
Center for Visual and Performing Arts
1040 Ridge Road
Munster, IN 46321
219-836-1930

Ceremony starts at 5 p.m.
Cocktail hour and reception to follow

Attire: Semi-formal (suit and tie for the gentlemen; cocktail dress, skirt or dress pants and nice top for the ladies)

For your convenience, the ceremony, cocktail hour and reception will all be held at the Center for Visual and Performing Arts. 

Special requests for dietary restrictions will be happily accommodated. 

![image](https://cloud.githubusercontent.com/assets/19656892/15659615/0ae5fe1a-2693-11e6-876b-ce8cd8d490c9.png)

**Comment by carlthuringer** [comment]
Added
